spring.application.name=booking-service

spring.datasource.url=${POSTGRES_URL}/booking_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Chi emette il jwt
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://10.0.2.2:8081/realms/roadies-app
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/roadies-app/protocol/openid-connect/certs

server.port=8083
travel-service.url=http://localhost:8082
user-service.url=http://localhost:8085

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# configurazione Retry
resilience4j.retry.instances.travelService.maxAttempts=3
resilience4j.retry.instances.travelService.waitDuration=2s
resilience4j.retry.instances.travelService.ignoreExceptions=feign.FeignException.Conflict

# configurazione Circuit Breaker
resilience4j.circuitbreaker.instances.travelService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.travelService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.travelService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.travelService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.travelService.ignoreExceptions=feign.FeignException.Conflict

# rabbit retry
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000ms

#i8n
spring.messages.basename=messages, i18n.list
spring.messages.fallback-to-system-locale=false

#Stripe
stripe.secret.key=${STRIPE_sk}
stripe.webhook.secret=${WHSEC}

#Minio
minio.url = http://localhost:9000
minio.access-key = ${MINIO_ADMIN}
minio.secret-key= ${MINIO_ADMIN_PASSWORD}
minio.bookingBucket= booking-documents

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB