spring.application.name=user-service

spring.datasource.url=${POSTGRES_URL}/user_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#chi emette il JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://10.0.2.2:8081/realms/roadies-app
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/roadies-app/protocol/openid-connect/certs

server.port=8085

#minio
minio.url=http://localhost:9000
minio.accessKey=${MINIO_ADMIN}
minio.secretKey=${MINIO_ADMIN_PASSWORD}

# Limiti per il caricamento dei file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configurazione Bucket MinIO
minio.documentBucket=user-documents
minio.avatarBucket=user-avatars

#i8n
spring.messages.basename=messages, i18n.list
spring.messages.fallback-to-system-locale=false

# Retry per l'invio dei messaggi
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=1000ms
spring.rabbitmq.template.retry.max-retries=3
spring.rabbitmq.template.retry.multiplier=2

#Retry per i listener
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms
spring.rabbitmq.listener.simple.retry.max-retries=3
spring.rabbitmq.listener.simple.retry.multiplier=2.0

# Se fallisce dopo 3 tentativi, non rimetterlo in coda normale
spring.rabbitmq.listener.simple.default-requeue-rejected=false

#Keycloak
keycloak.admin.username=${KEYCLOAK_ADMIN_USER}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}
