server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: travel-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/travels/**
          filters:
            - name: CircuitBreaker
              args:
                name: travel-service-circuit-breaker
                fallbackUri: forward:/fallback/travel
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service-circuit-breaker
                fallbackUri: forward:/fallback/user
        - id: review-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/reviews/**
          filters:
            - name: CircuitBreaker
              args:
                name: review-service-circuit-breaker
                fallbackUri: forward:/fallback/review
        - id: chat-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/chats/**
          filters:
            - name: CircuitBreaker
              args:
                name: chat-service-circuit-breaker
                fallbackUri: forward:/fallback/chat
        - id: booking-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - name: CircuitBreaker
              args:
                name: booking-service-circuit-breaker
                fallbackUri: forward:/fallback/booking
      default-filters:
        - TokenRelay #Inietta il token nella richiesta al microservizio

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/roadies-app

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10 #Guarda le ultime 10 richieste
        failureRateThreshold: 50 #Se il 50% è fallito apre il circuito dunque non invia richieste al microservizio
        waitDurationInOpenState: 10000 #Dopo 10s si puo riprovare
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s #Se non risponde in 3s considero fallita la richiesta
        cancelRunningFuture: true
      travel-service-circuit-breaker:
        timeout-duration:
          seconds: 3