server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:roadies.p12
    key-store-password: ${KEY_STORE_PASS}
    key-store-type: PKCS12
    key-alias: rd_cert
    key-password: ${KEY_STORE_PASS}
    protocol: TLS
    enabled-protocols: TLSv1.2

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: travel-service
          uri: lb://TRAVEL-SERVICE
          predicates:
            - Path=/api/v1/travels/**, /api/v1/activities/**, /api/v1/metadata/**
          filters:
            - name: CircuitBreaker
              args:
                name: travel-service-circuit-breaker
                fallbackUri: forward:/fallback/travel
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**, /api/v1/user-documents/**, /api/v1/friends/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service-circuit-breaker
                fallbackUri: forward:/fallback/user
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/v1/reviews/**
          filters:
            - name: CircuitBreaker
              args:
                name: review-service-circuit-breaker
                fallbackUri: forward:/fallback/review
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/v1/chats/**
          filters:
            - name: CircuitBreaker
              args:
                name: chat-service-circuit-breaker
                fallbackUri: forward:/fallback/chat
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/bookings/**, /api/v1/payments/**, /api/v1/booking-documents/**
          filters:
            - name: CircuitBreaker
              args:
                name: booking-service-circuit-breaker
                fallbackUri: forward:/fallback/booking

        - id: travel-service-docs
          uri: lb://TRAVEL-SERVICE
          predicates:
            - Path=/travel-service/v3/api-docs
          filters:
            - RewritePath=/travel-service/v3/api-docs, /v3/api-docs
        - id: user-service-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/v3/api-docs, /v3/api-docs
        - id: review-service-docs
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/v3/api-docs
          filters:
            - RewritePath=/review-service/v3/api-docs, /v3/api-docs
        - id: booking-service-docs
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking-service/v3/api-docs
          filters:
            - RewritePath=/booking-service/v3/api-docs, /v3/api-docs
      default-filters:
        - TokenRelay

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10 #Guarda le ultime 10 richieste
        failureRateThreshold: 50 #Se il 50 fallito apre il circuito dunque non invia richieste al microservizio
        waitDurationInOpenState: 10000 #Dopo 10s si puo riprovare
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s #Se non risponde in 3s considero fallita la richiesta
        cancelRunningFuture: true
      travel-service-circuit-breaker:
        timeout-duration:
          seconds: 3


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: travel-service
        url: /travel-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: review-service
        url: /review-service/v3/api-docs
      - name: booking-service
        url: /booking-service/v3/api-docs
