spring.datasource.url=jdbc:postgresql://booking-db:5432/booking_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# configurazione Retry
resilience4j.retry.instances.travelService.maxAttempts=3
resilience4j.retry.instances.travelService.waitDuration=2s
resilience4j.retry.instances.travelService.ignoreExceptions=feign.FeignException.Conflict

# configurazione Circuit Breaker
resilience4j.circuitbreaker.instances.travelService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.travelService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.travelService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.travelService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.travelService.ignoreExceptions=feign.FeignException.Conflict

# rabbit retry
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000ms

#Stripe
stripe.secret.key=${STRIPE_sk}
stripe.webhook.secret=${WHSEC}

#Minio bucket specifico
minio.bookingBucket=booking-documents