server.port=8082

spring.datasource.url=${POSTGRES_URL}/travel_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.retry.instances.booking-service.maxAttempts=3
resilience4j.retry.instances.booking-service.waitDuration=1s

#Minio bucket specifico
minio.travelBucket=travels

#Rabbit
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=3
spring.rabbitmq.listener.simple.retry.max-interval=10000ms
spring.rabbitmq.listener.simple.multiplier=2
spring.rabbitmq.listener.simple.default-requeue-rejected=false