spring.datasource.url=jdbc:postgresql://user-db:5432/user_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

keycloak.client.secret=${CLIENT_SECRET}
keycloak.admin.username=${KEYCLOAK_ADMIN}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}
keycloak.auth-server-url=http://keycloak:8080

# Override dei limiti condivisi: qui servono più grandi
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Minio bucket specifici
minio.documentBucket=user-documents
minio.avatarBucket=user-avatars

# Retry per l'invio dei messaggi
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=1000ms
spring.rabbitmq.template.retry.max-retries=3
spring.rabbitmq.template.retry.multiplier=2

#Retry per i listener
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms
spring.rabbitmq.listener.simple.retry.max-retries=3
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.default-requeue-rejected=false