spring.application.name=booking-service

spring.datasource.url=${POSTGRES_URL}/booking_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/roadies-app
server.port=8083
travel-service.url=http://localhost:8082

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# configurazione Retry
resilience4j.retry.instances.travelService.maxAttempts=3
resilience4j.retry.instances.travelService.waitDuration=2s
resilience4j.retry.instances.travelService.ignoreExceptions=feign.FeignException.Conflict

# configurazione Circuit Breaker
resilience4j.circuitbreaker.instances.travelService.registerHealthIndicator=true
# misura le ultime 10 chiamate
resilience4j.circuitbreaker.instances.travelService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.travelService.failureRateThreshold=50
# aspetta 5 secondi prima di testare se il servizio è tornato online
resilience4j.circuitbreaker.instances.travelService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.travelService.ignoreExceptions=feign.FeignException.Conflict

#Stripe
stripe.secret.key=${STRIPE_KEY}
stripe.webhook.secret=${WHSEC}

#Minio
minio.url = http://localhost:9000
minio.access-key = ${MINIO_ADMIN}
minio.secret-key= ${MINIO_ADMIN_PASSWORD}
minio.travelBucket= travels

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB