spring.application.name=user-service

spring.datasource.url=${POSTGRES_URL}/user_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Chi emette il jwt
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/roadies-app

server.port=8083

minio.url=http://localhost:9000
minio.accessKey=${MINIO_ADMIN}
minio.secretKey=${MINIO_ADMIN_PASSWORD}

# Limiti per il caricamento dei file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configurazione Bucket MinIO
minio.documentBucket=user-documents
