/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.travel

import com.google.gson.annotations.SerializedName
import java.math.BigDecimal
import java.util.UUID

/**
 * 
 *
 * @param id 
 * @param ownerId 
 * @param name 
 * @param continent 
 * @param country 
 * @param destination 
 * @param startingFromPrice 
 * @param type 
 * @param averageRating 
 * @param images 
 */


data class ActivitySummaryResponse (

    @SerializedName("id")
    val id: UUID? = null,

    @SerializedName("ownerId")
    val ownerId: String? = null,

    @SerializedName("name")
    val name: String? = null,

    @SerializedName("continent")
    val continent: Continent? = null,

    @SerializedName("country")
    val country: String? = null,

    @SerializedName("destination")
    val destination: String? = null,

    @SerializedName("startingFromPrice")
    val startingFromPrice: BigDecimal? = null,

    @SerializedName("type")
    val type: String? = null,

    @SerializedName("averageRating")
    val averageRating: Double? = null,

    @SerializedName("images")
    val images: List<ImageResponse>? = null

) {

    /**
     * 
     *
     * Values: EUROPE,ASIA,AMERICA,OCEANIA,AFRICA
     */
    enum class Continent(val value: String) {
        @SerializedName(value = "EUROPE") EUROPE("EUROPE"),
        @SerializedName(value = "ASIA") ASIA("ASIA"),
        @SerializedName(value = "AMERICA") AMERICA("AMERICA"),
        @SerializedName(value = "OCEANIA") OCEANIA("OCEANIA"),
        @SerializedName(value = "AFRICA") AFRICA("AFRICA");
    }

}

