/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.travel


import com.google.gson.annotations.SerializedName
import java.util.UUID

/**
 * 
 *
 * @param continent 
 * @param name 
 * @param description 
 * @param country 
 * @param destination 
 * @param address 
 * @param latitude 
 * @param longitude 
 * @param dayNumber 
 * @param imageIds 
 */


data class ActivityUpdateRequest (

    @SerializedName("continent")
    val continent: Continent,

    @SerializedName("name")
    val name: String? = null,

    @SerializedName("description")
    val description: String? = null,

    @SerializedName("country")
    val country: String? = null,

    @SerializedName("destination")
    val destination: String? = null,

    @SerializedName("address")
    val address: String? = null,

    @SerializedName("latitude")
    val latitude: Double? = null,

    @SerializedName("longitude")
    val longitude: Double? = null,

    @SerializedName("dayNumber")
    val dayNumber: Int? = null,

    @SerializedName("imageIds")
    val imageIds: List<UUID>? = null

) {

    /**
     * 
     *
     * Values: EUROPE,ASIA,AMERICA,OCEANIA,AFRICA
     */
    enum class Continent(val value: String) {
        @SerializedName(value = "EUROPE") EUROPE("EUROPE"),
        @SerializedName(value = "ASIA") ASIA("ASIA"),
        @SerializedName(value = "AMERICA") AMERICA("AMERICA"),
        @SerializedName(value = "OCEANIA") OCEANIA("OCEANIA"),
        @SerializedName(value = "AFRICA") AFRICA("AFRICA");
    }

}

