/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.travel


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param page 
 * @param propertySize 
 * @param sort 
 */


data class Pageable (

    @SerializedName("page")
    val page: Int? = null,

    @SerializedName("size")
    val propertySize: Int? = null,

    @SerializedName("sort")
    val sort: List<String>? = null

) {


}

