/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.travel

import com.google.gson.annotations.SerializedName
import java.time.OffsetDateTime
import java.util.UUID

/**
 * 
 *
 * @param id 
 * @param ownerId 
 * @param title 
 * @param description 
 * @param continent 
 * @param country 
 * @param destination 
 * @param latitude 
 * @param longitude 
 * @param durationDays 
 * @param createdAt 
 * @param updatedAt 
 * @param type 
 * @param departures 
 * @param activities 
 * @param tagScores 
 * @param images 
 */


data class TravelResponse (

    @SerializedName("id")
    val id: UUID? = null,

    @SerializedName("ownerId")
    val ownerId: String? = null,

    @SerializedName("title")
    val title: String? = null,

    @SerializedName("description")
    val description: String? = null,

    @SerializedName("continent")
    val continent: Continent? = null,

    @SerializedName("country")
    val country: String? = null,

    @SerializedName("destination")
    val destination: String? = null,

    @SerializedName("latitude")
    val latitude: Double? = null,

    @SerializedName("longitude")
    val longitude: Double? = null,

    @SerializedName("durationDays")
    val durationDays: Int? = null,

    @SerializedName("createdAt")
    val createdAt: OffsetDateTime? = null,

    @SerializedName("updatedAt")
    val updatedAt: OffsetDateTime? = null,

    @SerializedName("type")
    val type: String? = null,

    @SerializedName("departures")
    val departures: List<TravelDepartureResponse>? = null,

    @SerializedName("activities")
    val activities: List<ActivityResponse>? = null,

    @SerializedName("tagScores")
    val tagScores: List<TravelTagResponse>? = null,

    @SerializedName("images")
    val images: List<ImageResponse>? = null

) {

    /**
     * 
     *
     * Values: EUROPE,ASIA,AMERICA,OCEANIA,AFRICA
     */
    enum class Continent(val value: String) {
        @SerializedName(value = "EUROPE") EUROPE("EUROPE"),
        @SerializedName(value = "ASIA") ASIA("ASIA"),
        @SerializedName(value = "AMERICA") AMERICA("AMERICA"),
        @SerializedName(value = "OCEANIA") OCEANIA("OCEANIA"),
        @SerializedName(value = "AFRICA") AFRICA("AFRICA");
    }

}

