/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.travel


import com.google.gson.annotations.SerializedName
import java.math.BigDecimal
import java.time.LocalDate
import java.util.UUID

/**
 * 
 *
 * @param id 
 * @param startDate 
 * @param endDate 
 * @param price 
 */


data class TravelDepartureUpdateRequest (

    @SerializedName("id")
    val id: UUID? = null,

    @SerializedName("startDate")
    val startDate: LocalDate? = null,

    @SerializedName("endDate")
    val endDate: LocalDate? = null,

    @SerializedName("price")
    val price: BigDecimal? = null,

    @SerializedName("maxSlots")
    val maxSlots: Int? = null

) {


}

