/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.travel


import com.google.gson.annotations.SerializedName
import java.math.BigDecimal
import java.time.LocalDate
import java.util.UUID

/**
 * 
 *
 * @param id 
 * @param travelId 
 * @param startDate 
 * @param endDate 
 * @param price 
 * @param status 
 * @param maxSlots 
 * @param availableSlots 
 */


data class TravelDepartureResponse (

    @SerializedName("id")
    val id: UUID? = null,

    @SerializedName("travelId")
    val travelId: UUID? = null,

    @SerializedName("startDate")
    val startDate: LocalDate? = null,

    @SerializedName("endDate")
    val endDate: LocalDate? = null,

    @SerializedName("price")
    val price: BigDecimal? = null,

    @SerializedName("status")
    val status: Status? = null,

    @SerializedName("maxSlots")
    val maxSlots: Int? = null,

    @SerializedName("availableSlots")
    val availableSlots: Int? = null

) {

    /**
     * 
     *
     * Values: PLANNED,CONFIRMED,FULL
     */
    enum class Status(val value: String) {
        @SerializedName(value = "PLANNED") PLANNED("PLANNED"),
        @SerializedName(value = "CONFIRMED") CONFIRMED("CONFIRMED"),
        @SerializedName(value = "FULL") FULL("FULL");
    }

}

