/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.travel

import com.google.gson.annotations.SerializedName
import java.util.UUID

/**
 * 
 *
 * @param title 
 * @param description 
 * @param continent 
 * @param durationDays 
 * @param country 
 * @param destination 
 * @param latitude 
 * @param longitude 
 * @param imageIds 
 * @param departures 
 * @param activities 
 * @param tagScores 
 */


data class TravelCreateRequest (

    @SerializedName("title")
    val title: String,

    @SerializedName("description")
    val description: String,

    @SerializedName("continent")
    val continent: Continent,

    @SerializedName("durationDays")
    val durationDays: Int,

    @SerializedName("country")
    val country: String? = null,

    @SerializedName("destination")
    val destination: String? = null,

    @SerializedName("latitude")
    val latitude: Double? = null,

    @SerializedName("longitude")
    val longitude: Double? = null,

    @SerializedName("imageIds")
    val imageIds: List<UUID>? = null,

    @SerializedName("departures")
    val departures: List<TravelDepartureCreateRequest>? = null,

    @SerializedName("activities")
    val activities: List<ActivityCreateRequest>? = null,

    @SerializedName("tagScores")
    val tagScores: List<TravelTagRequest>? = null

) {

    /**
     * 
     *
     * Values: EUROPE,ASIA,AMERICA,OCEANIA,AFRICA
     */
    enum class Continent(val value: String) {
        @SerializedName(value = "EUROPE") EUROPE("EUROPE"),
        @SerializedName(value = "ASIA") ASIA("ASIA"),
        @SerializedName(value = "AMERICA") AMERICA("AMERICA"),
        @SerializedName(value = "OCEANIA") OCEANIA("OCEANIA"),
        @SerializedName(value = "AFRICA") AFRICA("AFRICA");
    }

}

