spring.application.name=travel-service

spring.datasource.url=${POSTGRES_URL}/travel_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Chi emette il jwt
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/roadies-app

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#Resilience4j
spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.retry.instances.booking-service.maxAttempts=3
resilience4j.retry.instances.booking-service.waitDuration=1s

#Minio
minio.url = http://localhost:9000
minio.access-key = ${MINIO_ADMIN}
minio.secret-key= ${MINIO_ADMIN_PASSWORD}
minio.travelBucket= travels
minio.activityBucket= activities

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

server.port=8082