spring.application.name=travel-service

spring.datasource.url=${POSTGRES_URL}/travel_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Chi emette il jwt
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/roadies-app

server.port=8082