spring.application.name=review-service
server.port=8084

# Database Configuration
spring.datasource.url=${POSTGRES_URL}/review_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Keycloak Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/roadies-app
# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html