/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param status 
 */


data class BookingStatusResponse (

    @SerializedName("status")
    val status: BookingStatusResponse.Status

) {

    /**
     * 
     *
     * Values: DRAFT,PENDING,RESERVE_CONFIRMED,RESERVE_REJECTED,READY_FOR_PAYMENT,CONFIRMED,CANCELLED,EXPIRED
     */
    enum class Status(val value: kotlin.String) {
        @SerializedName(value = "DRAFT") DRAFT("DRAFT"),
        @SerializedName(value = "PENDING") PENDING("PENDING"),
        @SerializedName(value = "RESERVE_CONFIRMED") RESERVE_CONFIRMED("RESERVE_CONFIRMED"),
        @SerializedName(value = "RESERVE_REJECTED") RESERVE_REJECTED("RESERVE_REJECTED"),
        @SerializedName(value = "READY_FOR_PAYMENT") READY_FOR_PAYMENT("READY_FOR_PAYMENT"),
        @SerializedName(value = "CONFIRMED") CONFIRMED("CONFIRMED"),
        @SerializedName(value = "CANCELLED") CANCELLED("CANCELLED"),
        @SerializedName(value = "EXPIRED") EXPIRED("EXPIRED");
    }

}

