/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param bookingId 
 * @param travelId 
 * @param activityId 
 * @param peopleCount 
 * @param validTarget 
 */


data class BookingCreateRequest (

    @SerializedName("bookingId")
    val bookingId: java.util.UUID,

    @SerializedName("travelId")
    val travelId: java.util.UUID? = null,

    @SerializedName("activityId")
    val activityId: java.util.UUID? = null,

    @SerializedName("peopleCount")
    val peopleCount: kotlin.Int? = null,

    @SerializedName("validTarget")
    val validTarget: kotlin.Boolean? = null

) {


}

