/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.booking

import it.roadies.android_app.client.models.MemberIdResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param bookingId 
 * @param members 
 */


data class BookingStep2Response (

    @SerializedName("bookingId")
    val bookingId: java.util.UUID? = null,

    @SerializedName("members")
    val members: kotlin.collections.List<MemberIdResponse>? = null

) {


}

