/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models

import it.roadies.android_app.client.models.MemberDocumentRequest

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param firstName 
 * @param lastName 
 * @param phoneNumber 
 * @param birthDate 
 * @param notes 
 * @param documents 
 */


data class BookingMemberDTO (

    @SerializedName("firstName")
    val firstName: kotlin.String,

    @SerializedName("lastName")
    val lastName: kotlin.String,

    @SerializedName("phoneNumber")
    val phoneNumber: kotlin.String,

    @SerializedName("birthDate")
    val birthDate: java.time.LocalDate? = null,

    @SerializedName("notes")
    val notes: kotlin.String? = null,

    @SerializedName("documents")
    val documents: kotlin.collections.List<MemberDocumentRequest>? = null

) {


}

