/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.booking


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param memberId 
 * @param firstName 
 * @param lastName 
 * @param documentIds 
 */


data class MemberIdResponse (

    @SerializedName("memberId")
    val memberId: java.util.UUID? = null,

    @SerializedName("firstName")
    val firstName: kotlin.String? = null,

    @SerializedName("lastName")
    val lastName: kotlin.String? = null,

    @SerializedName("documentIds")
    val documentIds: kotlin.collections.List<java.util.UUID>? = null

) {


}

