/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param paymentIntentId 
 * @param clientSecret 
 * @param status 
 */


data class PaymentResponse (

    @SerializedName("paymentIntentId")
    val paymentIntentId: kotlin.String? = null,

    @SerializedName("clientSecret")
    val clientSecret: kotlin.String? = null,

    @SerializedName("status")
    val status: kotlin.String? = null

) {


}

