/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param startTimestamp 
 * @param endTimestamp 
 * @param maxSlots 
 * @param price 
 */


data class ActivityDepartureCreateRequest (

    @SerializedName("startTimestamp")
    val startTimestamp: java.time.OffsetDateTime,

    @SerializedName("endTimestamp")
    val endTimestamp: java.time.OffsetDateTime,

    @SerializedName("maxSlots")
    val maxSlots: kotlin.Int,

    @SerializedName("price")
    val price: java.math.BigDecimal

) {


}

