/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param activityId 
 * @param startTimestamp 
 * @param endTimestamp 
 * @param maxSlots 
 * @param price 
 * @param status 
 * @param availableSlots 
 */


data class ActivityDepartureResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("activityId")
    val activityId: java.util.UUID? = null,

    @SerializedName("startTimestamp")
    val startTimestamp: java.time.OffsetDateTime? = null,

    @SerializedName("endTimestamp")
    val endTimestamp: java.time.OffsetDateTime? = null,

    @SerializedName("maxSlots")
    val maxSlots: kotlin.Int? = null,

    @SerializedName("price")
    val price: java.math.BigDecimal? = null,

    @SerializedName("status")
    val status: ActivityDepartureResponse.Status? = null,

    @SerializedName("availableSlots")
    val availableSlots: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: PLANNED,CONFIRMED,FULL
     */
    enum class Status(val value: kotlin.String) {
        @SerializedName(value = "PLANNED") PLANNED("PLANNED"),
        @SerializedName(value = "CONFIRMED") CONFIRMED("CONFIRMED"),
        @SerializedName(value = "FULL") FULL("FULL");
    }

}

