/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models

import it.roadies.android_app.client.models.ActivityDepartureResponse
import it.roadies.android_app.client.models.ImageResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param travelId 
 * @param ownerId 
 * @param name 
 * @param description 
 * @param continent 
 * @param country 
 * @param destination 
 * @param address 
 * @param latitude 
 * @param longitude 
 * @param dayNumber 
 * @param createdAt 
 * @param updatedAt 
 * @param type 
 * @param departures 
 * @param images 
 */


data class ActivityResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("travelId")
    val travelId: java.util.UUID? = null,

    @SerializedName("ownerId")
    val ownerId: kotlin.String? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("description")
    val description: kotlin.String? = null,

    @SerializedName("continent")
    val continent: ActivityResponse.Continent? = null,

    @SerializedName("country")
    val country: kotlin.String? = null,

    @SerializedName("destination")
    val destination: kotlin.String? = null,

    @SerializedName("address")
    val address: kotlin.String? = null,

    @SerializedName("latitude")
    val latitude: kotlin.Double? = null,

    @SerializedName("longitude")
    val longitude: kotlin.Double? = null,

    @SerializedName("dayNumber")
    val dayNumber: kotlin.Int? = null,

    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerializedName("updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null,

    @SerializedName("type")
    val type: kotlin.String? = null,

    @SerializedName("departures")
    val departures: kotlin.collections.List<ActivityDepartureResponse>? = null,

    @SerializedName("images")
    val images: kotlin.collections.List<ImageResponse>? = null

) {

    /**
     * 
     *
     * Values: EUROPE,ASIA,AMERICA,OCEANIA,AFRICA
     */
    enum class Continent(val value: kotlin.String) {
        @SerializedName(value = "EUROPE") EUROPE("EUROPE"),
        @SerializedName(value = "ASIA") ASIA("ASIA"),
        @SerializedName(value = "AMERICA") AMERICA("AMERICA"),
        @SerializedName(value = "OCEANIA") OCEANIA("OCEANIA"),
        @SerializedName(value = "AFRICA") AFRICA("AFRICA");
    }

}

