/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param visibility 
 */


data class FavouriteListCreateRequest (

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("visibility")
    val visibility: FavouriteListCreateRequest.Visibility

) {

    /**
     * 
     *
     * Values: PUBLIC,PRIVATE,SHARED_SPECIFIC
     */
    enum class Visibility(val value: kotlin.String) {
        @SerializedName(value = "PUBLIC") PUBLIC("PUBLIC"),
        @SerializedName(value = "PRIVATE") PRIVATE("PRIVATE"),
        @SerializedName(value = "SHARED_SPECIFIC") SHARED_SPECIFIC("SHARED_SPECIFIC");
    }

}

