/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models

import it.roadies.android_app.client.models.FavouriteListItemResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param ownerId 
 * @param name 
 * @param visibility 
 * @param createdAt 
 * @param items 
 */


data class FavouriteListResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("ownerId")
    val ownerId: kotlin.String? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("visibility")
    val visibility: FavouriteListResponse.Visibility? = null,

    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerializedName("items")
    val items: kotlin.collections.List<FavouriteListItemResponse>? = null

) {

    /**
     * 
     *
     * Values: PUBLIC,PRIVATE,SHARED_SPECIFIC
     */
    enum class Visibility(val value: kotlin.String) {
        @SerializedName(value = "PUBLIC") PUBLIC("PUBLIC"),
        @SerializedName(value = "PRIVATE") PRIVATE("PRIVATE"),
        @SerializedName(value = "SHARED_SPECIFIC") SHARED_SPECIFIC("SHARED_SPECIFIC");
    }

}

