/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models

import it.roadies.android_app.client.models.ActivitySummaryResponse
import it.roadies.android_app.client.models.TravelSummaryResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param addedAt 
 * @param travel 
 * @param activity 
 */


data class FavouriteListItemResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("addedAt")
    val addedAt: java.time.OffsetDateTime? = null,

    @SerializedName("travel")
    val travel: TravelSummaryResponse? = null,

    @SerializedName("activity")
    val activity: ActivitySummaryResponse? = null

) {


}

