/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models

import it.roadies.android_app.client.models.ActivitySummaryResponse
import it.roadies.android_app.client.models.TravelSummaryResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param travels 
 * @param activities 
 */


data class OrganizerTravelsActivityResponse (

    @SerializedName("travels")
    val travels: kotlin.collections.List<TravelSummaryResponse>? = null,

    @SerializedName("activities")
    val activities: kotlin.collections.List<ActivitySummaryResponse>? = null

) {


}

