/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models

import it.roadies.android_app.client.models.ImageResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param ownerId 
 * @param title 
 * @param continent 
 * @param country 
 * @param destination 
 * @param durationDays 
 * @param startingFromPrice 
 * @param type 
 * @param images 
 * @param averageRating 
 */


data class TravelSummaryResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("ownerId")
    val ownerId: kotlin.String? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("continent")
    val continent: TravelSummaryResponse.Continent? = null,

    @SerializedName("country")
    val country: kotlin.String? = null,

    @SerializedName("destination")
    val destination: kotlin.String? = null,

    @SerializedName("durationDays")
    val durationDays: kotlin.Int? = null,

    @SerializedName("startingFromPrice")
    val startingFromPrice: java.math.BigDecimal? = null,

    @SerializedName("type")
    val type: kotlin.String? = null,

    @SerializedName("images")
    val images: kotlin.collections.List<ImageResponse>? = null,

    @SerializedName("averageRating")
    val averageRating: kotlin.Double? = null

) {

    /**
     * 
     *
     * Values: EUROPE,ASIA,AMERICA,OCEANIA,AFRICA
     */
    enum class Continent(val value: kotlin.String) {
        @SerializedName(value = "EUROPE") EUROPE("EUROPE"),
        @SerializedName(value = "ASIA") ASIA("ASIA"),
        @SerializedName(value = "AMERICA") AMERICA("AMERICA"),
        @SerializedName(value = "OCEANIA") OCEANIA("OCEANIA"),
        @SerializedName(value = "AFRICA") AFRICA("AFRICA");
    }

}

