/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param startDate 
 * @param endDate 
 * @param price 
 * @param maxSlots 
 */


data class TravelDepartureCreateRequest (

    @SerializedName("startDate")
    val startDate: java.time.LocalDate,

    @SerializedName("endDate")
    val endDate: java.time.LocalDate,

    @SerializedName("price")
    val price: java.math.BigDecimal,

    @SerializedName("maxSlots")
    val maxSlots: kotlin.Int

) {


}

