/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param travelId 
 * @param startDate 
 * @param endDate 
 * @param price 
 * @param status 
 * @param maxSlots 
 * @param availableSlots 
 */


data class TravelDepartureResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("travelId")
    val travelId: java.util.UUID? = null,

    @SerializedName("startDate")
    val startDate: java.time.LocalDate? = null,

    @SerializedName("endDate")
    val endDate: java.time.LocalDate? = null,

    @SerializedName("price")
    val price: java.math.BigDecimal? = null,

    @SerializedName("status")
    val status: TravelDepartureResponse.Status? = null,

    @SerializedName("maxSlots")
    val maxSlots: kotlin.Int? = null,

    @SerializedName("availableSlots")
    val availableSlots: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: PLANNED,CONFIRMED,FULL
     */
    enum class Status(val value: kotlin.String) {
        @SerializedName(value = "PLANNED") PLANNED("PLANNED"),
        @SerializedName(value = "CONFIRMED") CONFIRMED("CONFIRMED"),
        @SerializedName(value = "FULL") FULL("FULL");
    }

}

