/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models

import it.roadies.android_app.client.models.ActivityResponse
import it.roadies.android_app.client.models.ImageResponse
import it.roadies.android_app.client.models.TravelDepartureResponse
import it.roadies.android_app.client.models.TravelTagResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param ownerId 
 * @param title 
 * @param description 
 * @param continent 
 * @param country 
 * @param destination 
 * @param latitude 
 * @param longitude 
 * @param durationDays 
 * @param createdAt 
 * @param updatedAt 
 * @param type 
 * @param departures 
 * @param activities 
 * @param tagScores 
 * @param images 
 */


data class TravelResponse (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("ownerId")
    val ownerId: kotlin.String? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("description")
    val description: kotlin.String? = null,

    @SerializedName("continent")
    val continent: TravelResponse.Continent? = null,

    @SerializedName("country")
    val country: kotlin.String? = null,

    @SerializedName("destination")
    val destination: kotlin.String? = null,

    @SerializedName("latitude")
    val latitude: kotlin.Double? = null,

    @SerializedName("longitude")
    val longitude: kotlin.Double? = null,

    @SerializedName("durationDays")
    val durationDays: kotlin.Int? = null,

    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerializedName("updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null,

    @SerializedName("type")
    val type: kotlin.String? = null,

    @SerializedName("departures")
    val departures: kotlin.collections.List<TravelDepartureResponse>? = null,

    @SerializedName("activities")
    val activities: kotlin.collections.List<ActivityResponse>? = null,

    @SerializedName("tagScores")
    val tagScores: kotlin.collections.List<TravelTagResponse>? = null,

    @SerializedName("images")
    val images: kotlin.collections.List<ImageResponse>? = null

) {

    /**
     * 
     *
     * Values: EUROPE,ASIA,AMERICA,OCEANIA,AFRICA
     */
    enum class Continent(val value: kotlin.String) {
        @SerializedName(value = "EUROPE") EUROPE("EUROPE"),
        @SerializedName(value = "ASIA") ASIA("ASIA"),
        @SerializedName(value = "AMERICA") AMERICA("AMERICA"),
        @SerializedName(value = "OCEANIA") OCEANIA("OCEANIA"),
        @SerializedName(value = "AFRICA") AFRICA("AFRICA");
    }

}

