/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models

import it.roadies.android_app.client.models.ActivityCreateRequest
import it.roadies.android_app.client.models.TravelDepartureCreateRequest
import it.roadies.android_app.client.models.TravelTagRequest

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param title 
 * @param description 
 * @param continent 
 * @param durationDays 
 * @param country 
 * @param destination 
 * @param latitude 
 * @param longitude 
 * @param imageIds 
 * @param departures 
 * @param activities 
 * @param tagScores 
 */


data class TravelCreateRequest (

    @SerializedName("title")
    val title: kotlin.String,

    @SerializedName("description")
    val description: kotlin.String,

    @SerializedName("continent")
    val continent: TravelCreateRequest.Continent,

    @SerializedName("durationDays")
    val durationDays: kotlin.Int,

    @SerializedName("country")
    val country: kotlin.String? = null,

    @SerializedName("destination")
    val destination: kotlin.String? = null,

    @SerializedName("latitude")
    val latitude: kotlin.Double? = null,

    @SerializedName("longitude")
    val longitude: kotlin.Double? = null,

    @SerializedName("imageIds")
    val imageIds: kotlin.collections.List<java.util.UUID>? = null,

    @SerializedName("departures")
    val departures: kotlin.collections.List<TravelDepartureCreateRequest>? = null,

    @SerializedName("activities")
    val activities: kotlin.collections.List<ActivityCreateRequest>? = null,

    @SerializedName("tagScores")
    val tagScores: kotlin.collections.List<TravelTagRequest>? = null

) {

    /**
     * 
     *
     * Values: EUROPE,ASIA,AMERICA,OCEANIA,AFRICA
     */
    enum class Continent(val value: kotlin.String) {
        @SerializedName(value = "EUROPE") EUROPE("EUROPE"),
        @SerializedName(value = "ASIA") ASIA("ASIA"),
        @SerializedName(value = "AMERICA") AMERICA("AMERICA"),
        @SerializedName(value = "OCEANIA") OCEANIA("OCEANIA"),
        @SerializedName(value = "AFRICA") AFRICA("AFRICA");
    }

}

