/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.user

import it.roadies.android_app.client.models.user.UserProfileResponseDTO

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param status 
 * @param createdAt 
 * @param friendProfile 
 */


data class FriendshipResponseDTO (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("status")
    val status: kotlin.String? = null,

    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerializedName("friendProfile")
    val friendProfile: UserProfileResponseDTO? = null

) {


}

