/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.user


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param keycloakId 
 * @param username 
 * @param firstName 
 * @param lastName 
 * @param email 
 * @param organizerRequestStatus 
 * @param organizerRequestedAt 
 */


data class PendingOrganizerRequestResponseDTO (

    @SerializedName("keycloakId")
    val keycloakId: kotlin.String? = null,

    @SerializedName("username")
    val username: kotlin.String? = null,

    @SerializedName("firstName")
    val firstName: kotlin.String? = null,

    @SerializedName("lastName")
    val lastName: kotlin.String? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("organizerRequestStatus")
    val organizerRequestStatus: PendingOrganizerRequestResponseDTO.OrganizerRequestStatus? = null,

    @SerializedName("organizerRequestedAt")
    val organizerRequestedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: NONE,PENDING,ACCEPTED,REJECTED
     */
    enum class OrganizerRequestStatus(val value: kotlin.String) {
        @SerializedName(value = "NONE") NONE("NONE"),
        @SerializedName(value = "PENDING") PENDING("PENDING"),
        @SerializedName(value = "ACCEPTED") ACCEPTED("ACCEPTED"),
        @SerializedName(value = "REJECTED") REJECTED("REJECTED");
    }

}

