/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.user


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param documentType 
 * @param documentNumber 
 */


data class UserDocumentRequestDTO (

    @SerializedName("documentType")
    val documentType: UserDocumentRequestDTO.DocumentType,

    @SerializedName("documentNumber")
    val documentNumber: kotlin.String

) {

    /**
     * 
     *
     * Values: ID_CARD,DRIVER_LICENSE,PASSPORT
     */
    enum class DocumentType(val value: kotlin.String) {
        @SerializedName(value = "ID_CARD") ID_CARD("ID_CARD"),
        @SerializedName(value = "DRIVER_LICENSE") DRIVER_LICENSE("DRIVER_LICENSE"),
        @SerializedName(value = "PASSPORT") PASSPORT("PASSPORT");
    }

}

