/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.user


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param documentType 
 * @param documentNumber 
 * @param fileUrl 
 * @param status 
 * @param rejectionReason 
 * @param createdAt 
 * @param userId 
 */


data class UserDocumentResponseDTO (

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("documentType")
    val documentType: UserDocumentResponseDTO.DocumentType? = null,

    @SerializedName("documentNumber")
    val documentNumber: kotlin.String? = null,

    @SerializedName("fileUrl")
    val fileUrl: kotlin.String? = null,

    @SerializedName("status")
    val status: UserDocumentResponseDTO.Status? = null,

    @SerializedName("rejectionReason")
    val rejectionReason: kotlin.String? = null,

    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerializedName("userId")
    val userId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: ID_CARD,DRIVER_LICENSE,PASSPORT
     */
    enum class DocumentType(val value: kotlin.String) {
        @SerializedName(value = "ID_CARD") ID_CARD("ID_CARD"),
        @SerializedName(value = "DRIVER_LICENSE") DRIVER_LICENSE("DRIVER_LICENSE"),
        @SerializedName(value = "PASSPORT") PASSPORT("PASSPORT");
    }
    /**
     * 
     *
     * Values: PENDING,VERIFIED,REJECTED
     */
    enum class Status(val value: kotlin.String) {
        @SerializedName(value = "PENDING") PENDING("PENDING"),
        @SerializedName(value = "VERIFIED") VERIFIED("VERIFIED"),
        @SerializedName(value = "REJECTED") REJECTED("REJECTED");
    }

}

