/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.user


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param email 
 * @param username 
 * @param firstName 
 * @param lastName 
 * @param birthDate 
 * @param keycloakId 
 */


data class UserSyncRequestDTO (

    @SerializedName("email")
    val email: kotlin.String,

    @SerializedName("username")
    val username: kotlin.String,

    @SerializedName("firstName")
    val firstName: kotlin.String,

    @SerializedName("lastName")
    val lastName: kotlin.String,

    @SerializedName("keycloakId")
    val keycloakId: kotlin.String? = null
) {


}

