/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package it.roadies.android_app.client.models.user


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param username 
 * @param firstName 
 * @param lastName 
 * @param avatarUrl 
 * @param points 
 * @param badge 
 */


data class UserProfileResponseDTO (

    @SerializedName("username")
    val username: kotlin.String? = null,

    @SerializedName("firstName")
    val firstName: kotlin.String? = null,

    @SerializedName("lastName")
    val lastName: kotlin.String? = null,

    @SerializedName("avatarUrl")
    val avatarUrl: kotlin.String? = null,

    @SerializedName("points")
    val points: kotlin.Long? = null,

    @SerializedName("badge")
    val badge: UserProfileResponseDTO.Badge? = null,

    @SerializedName("birthDate")
    val birthDate: java.time.LocalDate?

) {

    /**
     * 
     *
     * Values: BRONZE,SILVER,GOLD,PLATINUM,DIAMOND,EMERALD
     */
    enum class Badge(val value: kotlin.String) {
        @SerializedName(value = "BRONZE") BRONZE("BRONZE"),
        @SerializedName(value = "SILVER") SILVER("SILVER"),
        @SerializedName(value = "GOLD") GOLD("GOLD"),
        @SerializedName(value = "PLATINUM") PLATINUM("PLATINUM"),
        @SerializedName(value = "DIAMOND") DIAMOND("DIAMOND"),
        @SerializedName(value = "EMERALD") EMERALD("EMERALD");
    }

}

